### ISSUE TITLE
[추가사항] A* algorithm 추가

### ISSUE THREAD

**Issue by Minki-Kim95** [18-2-SKKU-OSS/javascript-algorithms#1]
주어진 출발 꼭짓점에서부터 목표 꼭짓점까지 가는 최단 경로를 찾아내는 그래프/트리 탐색 알고리즘

실제 프로젝트에서도 issue로 등록되어 있는 사항

**Comment by orist22** [comment]
이부분을 제가 Javascript로 구현해 추가하도록 하겠습니다

**Comment by Minki-Kim95** [comment]
> 이부분을 제가 Javascript로 구현해 추가하도록 하겠습니다

해당 issue에 대한 담당자로 임명해드렸습니다
