### ISSUE TITLE
[수정사항] 한글 번역

### ISSUE THREAD

**Issue by Minki-Kim95** [18-2-SKKU-OSS/javascript-algorithms#2]
한글 번역된 readMe를 보면 버블소트를 거품 정렬이라고 되있는 부분이 있는데 이 부분 혹시 버블 정렬로 바꾸는거 어떻게 생각하나요?

**Comment by orist22** [comment]
검색해보니까 여러 한글 해석에서 거품 정렬이라고 표현하고 있어서 그대로 거품 정렬이라고 해도 될 것 같습니다.

**Comment by Minki-Kim95** [comment]
그럼 다른 해석이 어색한 부분을 고쳐보도록 하겠습니다

**Comment by Minki-Kim95** [comment]
대신 거품정렬에 대한 부분은 옆에 괄호 치고 영어로 쓰는 방향으로 고쳐보겠습니다
